namespace Feda.Tests;

using NUnit.Framework;

[TestFixture]
public sealed class CoordinatesFixture
{
    [Test]
    [TestCase(0, 0, Square.A8)]
    [TestCase(1, 0, Square.A7)]
    [TestCase(2, 0, Square.A6)]
    [TestCase(3, 0, Square.A5)]
    [TestCase(4, 0, Square.A4)]
    [TestCase(5, 0, Square.A3)]
    [TestCase(6, 0, Square.A2)]
    [TestCase(7, 0, Square.A1)]
    [TestCase(0, 1, Square.B8)]
    [TestCase(1, 1, Square.B7)]
    [TestCase(2, 1, Square.B6)]
    [TestCase(3, 1, Square.B5)]
    [TestCase(4, 1, Square.B4)]
    [TestCase(5, 1, Square.B3)]
    [TestCase(6, 1, Square.B2)]
    [TestCase(7, 1, Square.B1)]
    [TestCase(0, 2, Square.C8)]
    [TestCase(1, 2, Square.C7)]
    [TestCase(2, 2, Square.C6)]
    [TestCase(3, 2, Square.C5)]
    [TestCase(4, 2, Square.C4)]
    [TestCase(5, 2, Square.C3)]
    [TestCase(6, 2, Square.C2)]
    [TestCase(7, 2, Square.C1)]
    [TestCase(0, 3, Square.D8)]
    [TestCase(1, 3, Square.D7)]
    [TestCase(2, 3, Square.D6)]
    [TestCase(3, 3, Square.D5)]
    [TestCase(4, 3, Square.D4)]
    [TestCase(5, 3, Square.D3)]
    [TestCase(6, 3, Square.D2)]
    [TestCase(7, 3, Square.D1)]
    [TestCase(0, 4, Square.E8)]
    [TestCase(1, 4, Square.E7)]
    [TestCase(2, 4, Square.E6)]
    [TestCase(3, 4, Square.E5)]
    [TestCase(4, 4, Square.E4)]
    [TestCase(5, 4, Square.E3)]
    [TestCase(6, 4, Square.E2)]
    [TestCase(7, 4, Square.E1)]
    [TestCase(0, 5, Square.F8)]
    [TestCase(1, 5, Square.F7)]
    [TestCase(2, 5, Square.F6)]
    [TestCase(3, 5, Square.F5)]
    [TestCase(4, 5, Square.F4)]
    [TestCase(5, 5, Square.F3)]
    [TestCase(6, 5, Square.F2)]
    [TestCase(7, 5, Square.F1)]
    [TestCase(0, 6, Square.G8)]
    [TestCase(1, 6, Square.G7)]
    [TestCase(2, 6, Square.G6)]
    [TestCase(3, 6, Square.G5)]
    [TestCase(4, 6, Square.G4)]
    [TestCase(5, 6, Square.G3)]
    [TestCase(6, 6, Square.G2)]
    [TestCase(7, 6, Square.G1)]
    [TestCase(0, 7, Square.H8)]
    [TestCase(1, 7, Square.H7)]
    [TestCase(2, 7, Square.H6)]
    [TestCase(3, 7, Square.H5)]
    [TestCase(4, 7, Square.H4)]
    [TestCase(5, 7, Square.H3)]
    [TestCase(6, 7, Square.H2)]
    [TestCase(7, 7, Square.H1)]
    public void GetSquare(int rank, int file, Square expected)
    {
        // Arrange - Act - Assert
        Assert.AreEqual(expected, Coordinates.GetSquare(rank, file));
    }
}